language: python
python:
    - 3.6
install:
    - pip install boto3
    - pip install utils
    - pip install moto
addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"
        token:
            secure: "VO/YIwEeQ/4TphtAMsQ/H65DvH15YGFngnmZoi4oMMCLNfv57BzWMumBZf8klzFyCQBTkmsjIbb8K51QqXaMTpUpnS6VFND/oGcXA6MJMI09zGrdlI5MuLJGzSdqY3x+5PTHQi0GTlIk/YZYfBk1mpky6NOpBSahznu5ozYj+qk7BRodSi5XDT1aq7w/gDUqBg4nKu91Bxy45zGjcVoLaR6TfRJsPSmH+WuubcNz82cVNuf2C6gezE8VUUsCDyurFKCSm5BYyEuGA+Lh7R+m5gcvNVtioRr+enyGqawYcmvKvj7Q9ZvDlk/In4MCgViep243VILgMJdfvX7LhHvSPl74UlI2vdgKAv/h5S1EdDBOQmqmi506GbKKUSm0gzwiw3suU3eL4L/8R8/2lGltgz7HF99+II8jJRohE39YOXBW/qhGgJpLs81B+8vXXAG4qC0LjFUl23c5p7WscrFeJSEN5HjUSKTBn05mSVDmPHZNPzxwa2Yz7yI6OeDhV6Udh3r5xle8btIbOJCp25goK77HGXOSOCEPX10m4KGCda1yYI5VkSLHKgRSaIf+1NTFzOI7ehTJ3JNDOdhtLzSW6E6xN9hy026TlM9wbgSTXreMFd6uh8Yoj41z6rD20jreocMXRT/tSAZX1jy5EciaP/x1HaqzGON6XZCsV45TMuQ="
script: 
    - python dataProcessor.py
    - sonar-scanner
